a=10
b=5
print(" Value of a before swapping=",a)
print(" Value of b before swapping=",b)
temp=a
a=b
b=temp
print("Values of a after swapping=",a)
print("Values of b after swapping=",b)
a=10
b=5
print(" Value of a before swapping=",a)
print(" Value of b before swapping=",b)
a=a+b
b=a-b
a=a-b
print("Values of a after swapping=",a)
print("Values of b after swapping=",b)

